### ISSUE TITLE
Where can I get the 3d models?

### ISSUE THREAD

**Issue by geocine** [perigoso/Switch_Keyboard#1]
Where is this located? `Switch_Keyboard_Kailh.3dshapes`. Are you willing to share it? I am specifically wanting the `Switch_Keyboard_Kailh.3dshapes/SW_Hotswap_Kailh.wrl`

**Comment by perigoso** [comment]
At the moment I don't have the 3d models included, they are linking to the location of the 3d models of the official libraries, but the official libraries don't include it right now either, i can't get you the model for cherry mx switches quickly, but i don't know that I've seen 3d models for the hotswap sockets

**Comment by geocine** [comment]
I am specifically looking for a WRL 3d model of a kailh hotswap socket, with textures included. What did you mean by this?
> i don't know that I've seen 3d models for the hotswap sockets
I actually found that model being referenced on your footprints

**Comment by perigoso** [comment]
I meant that I hadn't seen it modeled anywhere so I assumed it would have to be modeled from scratch, but I've found it now too.

**Comment by perigoso** [comment]
@geocine 3D models are now included as part of the library in [here](https://github.com/perigoso/Switch_Keyboard/tree/main/packages3d).
